# Generated by Django 4.0.5 on 2022-06-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(null=True),
        ),
    ]
