# Generated by Django 4.0.5 on 2022-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_ticket_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
