# Generated by Django 4.0.5 on 2022-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0003_ticket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
