# Generated by Django 4.0.5 on 2022-06-28 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_alter_ticket_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
